// Auto-generated
let project = new Project('SteelSoul_1_0_2');

project.addSources('Sources');
project.addLibrary("C:/Workspace/armsdk/armory");
project.addLibrary("C:/Workspace/armsdk/iron");
project.addLibrary("C:/Workspace/armsdk/lib/haxebullet");
project.addAssets("C:/Workspace/armsdk/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("C:/Workspace/armsdk/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.PlayerController');
project.addParameter("--macro keep('arm.PlayerController')");
project.addParameter('armory.trait.internal.UniformsManager');
project.addParameter("--macro keep('armory.trait.internal.UniformsManager')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addShaders("build_SteelSoul/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_SteelSoul/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_SteelSoul/compiled/Assets/**", { notinlist: true });
project.addAssets("build_SteelSoul/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("C:/Workspace/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addShaders("C:/Workspace/armsdk/armory/Shaders/debug_draw/line.vert.glsl");
project.addLibrary("C:/Workspace/armsdk/lib/zui");
project.addAssets("C:/Workspace/armsdk/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_clusters');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_background=World');
project.addDefine('js-es=6');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_assert_level=Warning');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_audio');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_morph_target');
project.addDefine('arm_particles');
project.addDefine('armory');


resolve(project);
